services:
  - type: web
    name: multi-agent-backend
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: false

  - type: web
    name: multi-agent-frontend
    runtime: node
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://multi-agent-backend.onrender.com
    autoDeploy: false 